---

- name: Install ONAP on rancher
  hosts: rancher
  roles: 
#    - { role: casablanca, tags: [ 'casablanca' ] }
#    - { role: dublin, tags: [ 'dublin' ] }
#    - { role: elalto, tags: [ 'elalto' ] }
    - { role: frankfurt, tags: [ 'frankfurt' ] }
  tasks: 

###

    - name: Display completed ip
      debug:
        msg: "Completed {{ansible_host}}" 
