---

- name: Set up workers 
  hosts: workers
  roles:
    - docker
    - ssh
#    - kubectl
#    - helm
    - nfs-common
    - nfs-share
#    - pnda
  tasks: 

###

    - name: Display completed ip
      debug:
        msg: "Completed {{ansible_host}}"

