---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - aws_keys.yml

  tasks:

  - name: Sync machine time with real time
    shell: sudo ntpdate us.pool.ntp.org
    register: sout

  - debug: var=sout.stdout_lines

  - name: Terraform step destroy
    shell: sudo terraform destroy -var-file="onap-deploy-properties.yml" -auto-approve
    register: sout

  - debug: var=sout.stdout_lines

  - name: Remove tfstate
    shell: sudo rm terraform.tfstate
    register: sout

  - debug: var=sout.stdout_lines

  - name: Remove backup tfstate
    shell: sudo rm terraform.tfstate.backup
    register: sout

  - debug: var=sout.stdout_lines

