---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    region: us-east-2
  vars_files:
    - aws_keys.yml

  tasks:
  - name: Read properties
    run_once: true
    include_vars:
      file: onap-deploy-properties.yml
      name: properties

  - name: Values from onap-release
    run_once: true
    debug: var=properties

  - name: Get EC2 instances
    run_once: true
    ec2_instance_facts:
      filters:
        "tag:Name": "{{ properties['node-prefix'] }}-*"
        instance-state-name: running
      region: "{{ region }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
    register: ec2cp

  - name: Terminate HA ONAP instances that were previously launched
    ec2:
      state: 'absent'
      instance_id: "{{ item.instance_id }}"
      region: "{{ region }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
    with_items: "{{ ec2cp.instances }}"

