---
# tasks file for ssh
- name: Read properties
  run_once: true
  include_vars:
    file: onap-deploy-properties.yml
    name: properties

- name: copy file
  template:
    src: "{{ properties['ssh-directory'] }}ohio-key-pair.pem"
    dest: "{{ properties['ssh-directory'] }}ohio-key-pair.pem"

