---
# tasks file for nfs-server
- name: Install nfs-kernel-server
  become: yes
  apt:
    name: nfs-kernel-server
    state: present

- name: MKDIR nfs_share
  become: yes
  file:
    path: /nfs_share
    state: directory
    mode: 0755

- name: CHOWN
  become: yes
  file:
    path: /nfs_share/
    owner: nobody
    group: nogroup

