---
# tasks file for rancher
#- name: Install rancher server
#  become: yes
#  command: docker run -d --restart=unless-stopped -p 8080:8080 --name rancher_server rancher/server:v1.6.22
#  register: sout

#- debug: var=sout.stdout_lines

- name: Read properties
  run_once: true
  include_vars:
    file: onap-deploy-properties.yml
    name: properties

#- name: Check if kubernetes is running
#  command: kubectl cluster-info
#  register: k8s_result
#  failed_when: k8s_result.rc == 1
#  ignore_errors: True

#- name: Remove /home/ubuntu/kube_config_rancher-cluster.yml before reinstalling RKE cluster
#  file:
#    state: absent
#    path: "{{ properties['baseline-directory'] }}kube_config_rancher-cluster.yml"
#  register: sout
#  when: k8s_result is failed

#- debug: var=sout
#  when: k8s_result is failed

#- name: Copy rke 
#  become: yes
#  copy:
#    src: "{{ properties['run-directory'] }}/rke"
#    dest: "{{ properties['baseline-directory'] }}"
#    mode: a+x

###
- name: WGET
  get_url:
    url: https://github.com/rancher/rke/releases/download/v1.0.6/rke_linux-amd64
    dest: "{{ properties['baseline-directory'] }}/rke"
    mode: a+x

- name: MV rke
  become: yes
  command: "mv {{ properties['baseline-directory'] }}/rke {{ properties['bin-directory'] }}rke"
###

- name: Copy cluster.yml file
  become: yes
  copy:
    src: "{{ properties['run-directory'] }}/cluster.yml"
    dest: "{{ properties['baseline-directory'] }}"

- name: Deploy K8S cluster using RKE
#  shell: sudo /home/ubuntu/rke up --config /home/ubuntu/cluster.yml
  shell: "rke up --config {{ properties['baseline-directory'] }}/cluster.yml"
  register: sout

- debug: var=sout.stdout_lines
#  when: k8s_result is failed

#- name: Wait for kube_config_cluster.yml
#  wait_for:
#    path: /home/ubuntu/kube_config_rancher-cluster.yml

